### PR TITLE
Debug without die

### PR DESCRIPTION
**Pull request by mtereschenko**
Quite often there is a need to debug without die
like 
```
function a($arg1, $arg2) {
   d($arg1);
   //some code
   dd($arg1);
}
```

### CODE REVIEW

**Comment by marktopper** [comment]
Awesome thanks!

**Comment by mtereschenko** [comment]
Will wait for it in master) Thanks)

**Comment by marktopper** [comment]
Merged to master and released as [`v1.1`](https://github.com/larapack/dd/releases/tag/v1.1).

**Comment by mtereschenko** [comment]
Thanks

**Pull request merged**
